#!/bin/bash

get-date() {
  date "+%A-%R-%d-%m-%y"
}

freeze-select() {
  grim - | imv -f -w "imv-screenshot" - &
  imv_pid=$!
}

outline_color="0.38,0.68,0.93"

while [[ "$1" ]]; do
  case "$1" in
  select | s)
    freeze-select
    grim -g "$(slurp -d)" "$HOME/Pictures/screenshots/$(get-date).png"
    kill $imv_pid
    ;;
  select-copy | scp)
    freeze-select
    maim -us -c $outline_color -b 4 | xclip -selection clipboard -t image/png
    kill $imv_pid
    ;;
  full | f)
    maim -u "$HOME/Pictures/screenshots/$(get-date).png"
    ;;
  full-copy | fcp)
    maim -u | xclip -selection clipboard -t image/png
    ;;
  esac
  exit
done
