#!/usr/bin/env bash

if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [[ -x "$f" ]] && . "$f"
  done
  unset f
fi


setxkbmap br &
numlockx on &
xset r rate 500 30 s 0 -dpms &
xsetroot -cursor_name left_ptr &

dunst &
dex -a -s $HOME/.config/autostart:$HOME/.config/autostart/xorg &


exec bspwm
