#!/usr/bin/env bash

bspc monitor DP-1 -d 1 2 3 4 5 6

bspc config pointer_motion_interval   5
bspc config pointer_follows_monitor   true
bspc config focus_follows_pointer     true
bspc config ignore_ewmh_focus         true
bspc config remove_unplugged_monitors true
bpsc config remove_disabled_monitors  true

bspc config border_width  2
bspc config window_gap    8

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color  "#61afef"
bspc config normal_border_color   "#1e222a"
bspc config presel_feedback_color "#98c379"

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"

# Ordering windows
bspc rule -a kitty            desktop='^1' follow=on
bspc rule -a Google-chrome    desktop='^2' follow=on
bspc rule -a Brave-browser    desktop='^2' follon=on
bspc rule -a discord          desktop='^3'
bspc rule -a TelegramDesktop  desktop='^3'
bspc rule -a Evince           desktop='^3'
bspc rule -a vlc              desktop='^4'
bspc rule -a Code             desktop='^5'
bspc rule -a jetbrains-studio desktop='^5'
bspc rule -a Gimp-2.10        desktop='^5'
bspc rule -a Steam            desktop='^6'
bspc rule -a Lutris           desktop='^6'
bspc rule -a qBittorrent      desktop='^6'
bspc rule -a DBeaver          dekstop='^6'

bspc rule -a feh                                 state=floating
bspc rule -a imv                                 state=floating
bspc rule -a org.gnome.Nautilus                  state=floating
bspc rule -a gnome-calculator                    state=floating
bspc rule -a Gufw.py                             state=floating
bspc rule -a Gcolor3                             state=floating
bspc rule -a File-roller                         state=floating

# Games
bspc rule -a hl2_linux                desktop='^5'

steamlib=$HOME/.steam/steam/
mygames=$(find "${steamlib}/steamapps" -iname "*.acf" | awk -F'[_.]' '{print $(NF-1)}')

for game in $mygames; do
  bspc rule -a steam_app_"$game" desktop='^5'
done

## Autostart
# Polybar
#$HOME/.config/polybar/launch.sh &

# Eww bar
"$HOME"/.config/eww/launch.sh &

killall -q sxhkd; sxhkd &
# setxkbmap br &
