# yazi.toml

[manager]
sort_dir_first = true
sort_by = "natural"
linemode = "size"

# Plugins
## Git
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
