#!/usr/bin/env bash

if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [[ -x "$f" ]] && . "$f"
  done
  unset f
fi


setxkbmap br &
# numlockx on &
xset r rate 500 30 s 0 &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# xss-lock --transfer-sleep-lock -- ~/scripts/xorg/lock &
# redshift -PO 4500K &
dunst &
flameshot &
~/scripts/random-wallpaper &


exec bspwm
