#!/bin/bash

icon_font="Material-Design-Icons"
font="JetBrains Mono Medium Nerd Font Complete"
image_path="$(cat ~/.cache/scripts/current_wallpaper)"
temp_path="/tmp/temp_image.png"

background_ring="#1a1b26"
background_inside="#16161ecc"
background_inside_no_opacity="#16161e"
font_color="#a9b1d6"
green="#9ece6a"
red="#f7768e"
blue="#7aadf7"

player_status="$(playerctl status)"

pre_lock() {
  # Screenshot, blur, darkens the image and add a lock icon
  convert "$image_path" \
    -blur 0x6 \
    -gamma 0.4 \
    -gravity Center \
    -font $icon_font \
    -pointsize 80 \
    -fill white -stroke black -strokewidth 2 \
    -annotate +0-3 󰌾 \
    $temp_path

  if [[ "$player_status" == "Playing" ]]; then
    playerctl pause
  fi
}

post_lock() {
  if [[ $player_status == "Playing" ]]; then
    playerctl play
  fi

  [[ -f $temp_path ]] && rm $temp_path
}

pre_lock

swaylock -f \
  --ignore-empty-password \
  --indicator-radius 100 \
  --key-hl-color=$green \
  --bs-hl-color=$red \
  --line-uses-inside \
  --separator-color=$background_ring \
  --inside-color=$background_inside \
  --inside-ver-color=$background_inside_no_opacity \
  --inside-wrong-color=$background_inside_no_opacity \
  --ring-color=$background_ring \
  --ring-ver-color=$blue \
  --ring-wrong-color=$red \
  --font="$font" \
  -i $temp_path --scaling=fill

post_lock
