#!/usr/bin/env bash

wid=$1
class=$2


_xprop() {
  xprop -notype -id "$wid" "$1" | cut -d\" -f"$2"
}

_steam() {
  wm_name="$(_xprop WM_NAME 2)"
  if [[ "$wm_name" = "Friends List" ]]; then
    echo "state=floating"
  elif [[ "$wm_name" = "Steam Guard - Computer Authorization Required" ]]; then
    echo "state=floating"
  fi
}

_steam_app_0() {
  wm_name="$(_xprop WM_NAME 2)"
  if [[ "$wm_name" = "Far Cry® 3" ]]; then
    echo "desktop='^5'"
  elif [[ "$wm_name" = "Ubisoft Connect" ]]; then
    echo "desktop='^3' border=off"
  fi
}

_spotify() {
  echo "desktop=^4"
}


main() {
  case "$class" in
    Steam)
      _steam
      ;;
    steam_app_0)
      _steam_app_0
      ;;
    [Ss]potify)
      _spotify
      ;;
    "")
      sleep 0.2
      class="$(_xprop WM_CLASS 4)"
      [[ -n "$class" ]] && main
      ;;
  esac
}
main
