#!/bin/bash

INPUT_EXT=".mkv"
OUTPUT_EXT=".mp4"
FILE_PATH="$1"
CODEC="265"
[[ -n "$2" ]] && CODEC=$2

compress-mkv() {
  if [[ "$CODEC" = "264" ]]; then
    ffmpeg -vaapi_device /dev/dri/renderD128 -i "$1" -vf 'scale=iw-mod(iw\,16):ih-mod(ih\,16),format=nv12,hwupload' -c:v hevc_vaapi -c:a aac -b:a 128k -b:v 2M -y "${1%.*}${OUTPUT_EXT}"
  else
    ffmpeg -i "$1" -vcodec libx265 -c:a copy -crf 23 -preset fast -y "${1%.*}${OUTPUT_EXT}"
  fi
}

mapfile -t FILES <<<"$(find "$FILE_PATH" -iname "*${INPUT_EXT}")"
[[ -z "${FILES[*]}" ]] && exit

for file in "${FILES[@]}"; do
  compress-mkv "${file}" &&
    rm "${file}"
done
