#!/bin/bash

# Colors
END="\033[0m"
RED="\033[1;31m"

# Compact
c() {
  METHODS="tar.gz tar.bz2 tar.xz tar.zst gz bz2 xz zst tar tbz2 tgz zip 7z rar"
  [[ -d "$1" ]] && METHODS="$(echo "$METHODS" | sed "s/ gz bz2 xz zst//")"
  if [[ -e "$1" ]]; then
    METHOD="$(echo "$METHODS" | tr \  \\n | fzf --prompt="Choose a compression method: ")"

    case "$METHOD" in
      tar.gz)  tar czvf "$1.tar.gz" "$1"                           ;;
      tar.bz2) tar cjvf "$1.tar.bz2" "$1"                          ;;
      tar.xz)  tar cJvf "$1.tar.xz" "$1"                           ;;
      tar.zst) tar cvf "$1.tar.zst" -I "zstd --ultra -22 -T0" "$1" ;;
      tar)     tar cvf "$1.tar" "$1"                               ;;
      gz)      gzip -9 -k "$1"                                     ;;
      bz2)     bzip2 -9 -k "$1"                                    ;;
      xz)      xz -9 -k "$1"                                       ;;
      zst)     zstd --ultra -22 -T0 -f -v "$1"                     ;;
      tgz)     tar czvf "$1.tgz" "$1"                              ;;
      tbz2)    tar cjvf "$1.tbz2" "$1"                             ;;
      zip)     zip -r "$1.zip" "$1"                                ;;
      7z)      7z a "$1.7z" "$1"                                   ;;
      rar)     rar a "$1.rar" "$1"                                 ;;
      *)
        echo -e "${RED}\"$METHOD\" is not available.${END}"   ;;
    esac
  else
    echo -e "${RED}\"$1\" is not a valid file.${END}"
  fi
}

# Extract
x() {
  if [[ -f $1 ]]; then
    case "$1" in
      *.tar.gz)   tar xvf "$1"               ;;
      *.tar.bz2)  tar xvf "$1"               ;;
      *.tar.xz)   tar xvf "$1"               ;;
      *.tar.zst)  tar xvf "$1" -I "zstd -T0" ;;
      *.tar)      tar xvf "$1"               ;;
      *.gz)       gunzip  "$1"               ;;
      *.bz2)      bunzip2 "$1"               ;;
      *.xz)       xz -d   "$1"               ;;
      *.zst)      zstd -d "$1" -T0 -f -v     ;;
      *.tgz)      tar xzf "$1"               ;;
      *.tbz2)     tar xjf "$1"               ;;
      *.zip)      unzip   "$1"               ;;
      *.7z)       7z x    "$1"               ;;
      *.rar)      unrar x "$1"               ;;
      *)
        echo "${RED}\"$1\" cannot be extracted via x().${END}" ;;
    esac
  else
    echo -e "${RED}\"$1\" is not a valid file.${END}"
  fi
}

"$@"
