#!/bin/sh

up() {
  docker-compose -f "$DCFG/${1}/docker-compose.yaml" up -d
}

down() {
  docker-compose -f "$DCFG/${1}/docker-compose.yaml" down
}

pull() {
  if [ "$1" = "-a" ]; then
    find "$DCFG" -maxdepth 2 -type f -iname "docker-compose.yaml" -exec docker-compose -f {} pull \;
    return
  fi
  docker-compose -f "$DCFG/${1}/docker-compose.yaml" pull
}

new() {
  [ -d "$DCFG/${1}" ] && mkdir "$DCFG/${1}"
  nvim "$DCFG/${1}/docker-compose.yaml"
}

"$@"
