#!/bin/bash

# Colors
END="\033[0m"
WHITE="\033[1;97m"
GREEN="\033[1;32m"

WALL_PATH="$XDG_PICTURES_DIR/wallpapers"
CACHE_FILE="$XDG_CACHE_HOME/scripts/wallpapers_left"

reset() {
  find "$WALL_PATH" -iname "*.jpg" | shuf | while read -r image; do
    echo "$image" >>"$CACHE_FILE"
  done
}

# If there's no more images, reset wallpapers_left.txt
[[ -z "$(cat "$CACHE_FILE")" ]] && reset

NEXT_WALLPAPER=$(head -n1 "$CACHE_FILE")
WALLPAPER_NAME="${NEXT_WALLPAPER##*/}"

if [[ "$XDG_SESSION_TYPE" = "wayland" ]]; then
  pidof -q swaybg && killall swaybg
  swaybg -i "${NEXT_WALLPAPER}" &
  disown
else
  feh --no-fehbg --bg-fill "${NEXT_WALLPAPER}"
fi

sed -i "/${WALLPAPER_NAME}/d" "$CACHE_FILE"
echo "$NEXT_WALLPAPER" >"$XDG_CACHE_HOME/scripts/current_wallpaper"

echo -e "  Selected the wallpaper: ${GREEN}\"${WALLPAPER_NAME}\"${END},
       \r  and removed it from ${WHITE}\"${CACHE_FILE}\"${END}."
