#!/bin/bash

# Colors
END="\033[0m"
RED="\033[0;31m"
GREEN="\033[1;32m"

declare -A resolutions
resolutions[FHD]="1920x1080"
resolutions[QHD]="2560x1440"
resolutions[4K]="3840x2160"

path="$XDG_PICTURES_DIR/wallpapers"
wallpapers=($(find "$path" -iname "*.jpeg"))
declare -a wrong_resolutions

for image in "${wallpapers[@]}"; do
  suposed_size=$(echo "$image" | awk -F "[()]" '{ print $2 }')
  actual_size=$(identify -format "%wx%h" "$path/$image")

  for size in "${!resolutions[@]}"; do
    if [[ "$suposed_size" == "$size" ]]; then
      if [[ "$actual_size" != "${resolutions[$size]}" ]]; then
        echo -e "${RED}$image${END}\n  Size: $actual_size\n"
        wrong_resolutions+=("yes")
      fi
    fi
  done
done

if [[ ! ${wrong_resolutions[*]} ]]; then
  echo -e "${GREEN}There's no images with wrong resolutions${END}\n"
fi
