#!/bin/sh

up() {
  docker-compose -f "$DCFG/${1}/docker-compose.yaml" up -d
}

down() {
  docker-compose -f "$DCFG/${1}/docker-compose.yaml" down
}

pull() {
  if [ "$1" = "-a" ]; then
    find "$DCFG" -maxdepth 2 -type f -iname "docker-compose.yaml" -exec docker-compose -f {} pull \;
    if [ "$2" = "-u" ]; then
      docker ps --format "{{.Names}}" | while read -r container; do
        if [ -f "$DCFG/${container}/docker-compose.yaml" ]; then
          docker-compose -f "$DCFG/${container}/docker-compose.yaml" up -d
        fi
      done
    fi
    return
  fi
  docker-compose -f "$DCFG/${1}/docker-compose.yaml" pull
}

new() {
  [ -d "$DCFG/${1}" ] && mkdir "$DCFG/${1}"
  nvim "$DCFG/${1}/docker-compose.yaml"
}

"$@"
